changelog:
  exclude:
    labels:
      - bluesky-ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - bluesky-Semver-Major
        - breaking-change
    - title: New Features
      labels:
        - bluesky-Semver-Minor
    - title: Bug Fixes
      labels:
        - bluesky-bug
    - title: Other Changes
      labels:
        - bluesky-documentation
        - "*"
