name: Check PR has release labels
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  has_label:
    name: Check PR has release labels
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR does not have a release label."
          exit 1
        if: |
          !contains(github.event.pull_request.labels.*.name, 'bluesky-bug') &&
          !contains(github.event.pull_request.labels.*.name, 'bluesky-Semver-Major') &&
          !contains(github.event.pull_request.labels.*.name, 'bluesky-Semver-Minor') &&
          !contains(github.event.pull_request.labels.*.name, 'bluesky-documentation') &&
          !contains(github.event.pull_request.labels.*.name, 'bluesky-ignore-for-release')
