name: sphinx

on: [push, pull_request, workflow_call]

jobs:
  call_sphinx_builder:
    uses: ISISComputingGroup/reusable-workflows/.github/workflows/sphinx.yml@main
    secrets: inherit
  vale:
    uses: errata-ai/vale-action@v2.1.1

