name: Publish Python distribution to PyPI
on: push
jobs:
  lint-and-test: 
    if: github.ref_type == 'tag'
    name: Run linter and tests
    uses: ./.github/workflows/Linter.yml
  build: 
    needs: lint-and-test
    if: github.ref_type == 'tag'
    name: build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
