name: future-dependency-compatibility-test
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.version }}
      - name: install requirements
        run: pip install -e .[dev]
      - name: install latest bluesky, ophyd-async and event-model
        run: pip install --upgrade --force-reinstall git+https://github.com/bluesky/bluesky.git@main git+https://github.com/bluesky/ophyd-async.git@main git+https://github.com/bluesky/event-model.git@main
      - name: run ruff
        run: python -m ruff check
        if: always()
      - name: run pyright
        run: python -m pyright
        if: always()
      - name: run pytest
        run: python -m pytest
        if: always()

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [tests]
    steps:
    - run: exit 1
      # see https://stackoverflow.com/a/67532120/4907315
      if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
